In [1]:
import numpy as np

#a.Импортируйте библиотеку NumPy

In [2]:
m1 = np.array([[0,0,0,0,0],
         [0,0,0,0,0]])
print(m1)

[[0 0 0 0 0]
 [0 0 0 0 0]]


In [3]:
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [4]:
a=np.zeros((5,2))
print(a)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


#b.Создайте массив из 10 нулей

In [6]:
m2 = np.array([[1,1,1,1,1],
         [1,1,1,1,1]])
print(m2)

[[1 1 1 1 1]
 [1 1 1 1 1]]


In [8]:
a=np.ones(10)
print(a)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#c.Создать массив из 10 единиц

In [7]:
m3 = np.array([[5,5,5,5,5],
         [5,5,5,5,5]])
print(m3)

[[5 5 5 5 5]
 [5 5 5 5 5]]


#d.Создать массив из 10 пятерок

In [10]:
for m5 in range (10,51):
 print(m5)

10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50


In [11]:
for m5 in reversed(range(10,51)):
 print(m5)

50
49
48
47
46
45
44
43
42
41
40
39
38
37
36
35
34
33
32
31
30
29
28
27
26
25
24
23
22
21
20
19
18
17
16
15
14
13
12
11
10


#e.Создать массив из целых чисел от 10 до 50

In [12]:
m8=np.arange(10,52,2)
print(m8)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


#f. Создать массив из четных чисел от 10 до 50

In [13]:
m9=np.arange(0,9).reshape(3,3)
print(m9)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#g.Создать матрицу 3х3 с числами от 0 до 8

In [14]:
m10=np.ones(9). reshape(3,3)
print(m10)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


#h.Создать единичную матрицу 3x3

In [18]:
x1=np.random.randint(2)
print(x1)

0


#i.Используйте NumPy для генерации случайного числа от 0 до 1

In [19]:
x= np.random.normal(0,1,25)
print(x)

[ 0.7296988   2.78172093 -1.43420859  0.70194071  0.02321741  0.75429963
  0.18709041 -0.0426019   0.17200641  1.37149793  0.34150196  1.28906364
 -0.97542658  1.29205961  1.15072834 -0.39563214 -0.49308702  2.40986964
  0.72557102 -1.1817827   0.45333429  1.39800022  0.4005969   0.35599518
  2.05289708]



#j.Используйте NumPy для генерации массива из 25 случайных чисел,взятых из стандартного нормального распределения

In [29]:
 m7 = np.linspace (0,1,101)
print(m7)

[0.   0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1  0.11 0.12 0.13
 0.14 0.15 0.16 0.17 0.18 0.19 0.2  0.21 0.22 0.23 0.24 0.25 0.26 0.27
 0.28 0.29 0.3  0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4  0.41
 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5  0.51 0.52 0.53 0.54 0.55
 0.56 0.57 0.58 0.59 0.6  0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69
 0.7  0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8  0.81 0.82 0.83
 0.84 0.85 0.86 0.87 0.88 0.89 0.9  0.91 0.92 0.93 0.94 0.95 0.96 0.97
 0.98 0.99 1.  ]


m15=np.arange(0.01,1.01,0.01), reshape(10,10)
print(m15)

In [25]:
mat=np.arange(0.01,1.01,0.01).reshape(10,10)
print(mat)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


#k.Создайте следующую матрицу используя функции библиотеки NumPy

In [30]:
mat = np.arange(1,26).reshape(5,5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


# l.Дана стартовая матрица (обязательно запустите код ниже в вашемрешении!). Эта матрица будет использоваться в последующих задачах

In [32]:
print('array',mat[2:,1:])

array [[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


Необходимо написать код который вернет следующую матрицуиз стартовой:

In [33]:
r=mat[mat==20]
print(r)

[20]


#m.Написать код обращения к элементу который вернет значение  20 изстартовой матрицы задачи l

In [37]:
print('array', mat[0:3,1]. reshape(3,1))

array [[ 2]
 [ 7]
 [12]]


#n.Написать код к стартовой матрице задачи l , который воспроизводитвывод, показанный ниже

In [38]:
print('array', mat[4:])

array [[21 22 23 24 25]]


#o.Написать код к стартовой матрице задачи l , который воспроизводитвывод, показанный ниже

In [39]:
print('f=', mat[3:])

f= [[16 17 18 19 20]
 [21 22 23 24 25]]


#p.Написать код к стартовой матрице задачи l , который воспроизводитвывод, показанный ниже

In [40]:
print(mat.sum())

325


#q.Получить сумму всех значений в стартовой матрице mat

In [41]:
print(mat.std())

7.211102550927978


# r.Получить стандартное отклонение в стартовой матрице mat

In [42]:
print(mat.sum(axis=0))

[55 60 65 70 75]


# s.Получить сумму значений в колонках в стартовой матрице mat